# .github/workflows/merge.yml (Version nettoyée)

name: Auto Merge PR

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  automerge:
    permissions:    
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Auto Merge
        uses: pascalgn/automerge-action@v0.16.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          merge-method: squash
          commit-message: title+body
          title: 'Merge automatique de la PR'
          # La ligne body doit être la dernière du bloc with:
          body: 'Cette PR a été fusionnée automatiquement.'